#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_STRING 50
#define MAX_BICICLETAS 15

#define MIN_UTENTES 1
#define MAX_UTENTES 50

#define MIN_DESIGNACAO 0
#define MAX_DESIGNACAO 9999

#define MAX_TELEFONE 999999999
#define MIN_TELEFONE 0


#define MAX_TIPO 4
#define MIN_TIPO 1

#define MIN_NUMERO_UTENTE 0
#define MAX_NUMERO_UTENTE 9999

#define RESID_CAMPUS1 4
#define CAMPUS1_CAMPUS2 2
#define CAMPUS2_CAMPUS5 1

#endif // CONSTANTES_H_INCLUDED
